name: MLops CI # the name of process

on: 
  workflow_dispatch: {}

jobs: # steps or missions
  e2e_mlops_workflow:
    runs-on: ubuntu-latest
    steps:
      - name: Checkout code # check the code in repo
        uses: actions/checkout@v5

      - name: Set up Python # setup python version
        uses: actions/setup-python@v6
        with:
          python-version: '3.12'

      - name: Install dependecies # install dependencies with some command
        run: | # run is CMD and | -> for writing multiple command line
          python -m pip install --upgrade pip
          pip install -r requirements.txt

      - name: Do Feature Engineering # create the feature-engin code
        run: |
          python src/features/engineering.py

      - name: Setup MLflow # to run mlflow with docker image before run train model, we add [mlflow-server] name for container to be easly stop next 
        run: |
          docker pull ghcr.io/mlflow/mlflow:latest 
          docker run -d -p 5555:5000 --name mlflow-server ghcr.io/mlflow/mlflow:latest \
            mlflow server --host 0.0.0.0 \
            --backend-store-uri sqlite:///mlflow.db \
            --default-artifact-root /tmp/mlruns

      - name: Train the Model # create the model based on config and mlflow
        run: |
          python src/models/trained_model.py

      - name: Cleaning up MLflow # for cleaning mlflow with stop container in container name [mlflow-server]
        run: |
          docker stop mlflow-server
          docker rm mlflow-server
          docker rmi ghcr.io/mlflow/mlflow:latest

      - name: Login to Docker Hub # to connect with docker hub
        uses: docker/login-action@v3
        with:
          username: ${{ vars.DOCKERHUB_USERNAME }}
          password: ${{ secrets.DOCKERHUB_TOKEN }}

      - name: Set up Docker Buildx # it's a builder configuration for docker
        uses: docker/setup-buildx-action@v3

      - name: Build Push # for building the images and pull it to dockerhub
        uses: docker/build-push-action@v6
        with:
          push: true
          tags: magdy288/fastapi:${{ github.sha }} # [sha] -> is hash the tag version for every time commit the repo changes creating new tag for container 
          context: "." # the dir of Dockerfile
          file: "Dockerfile"